# Pivoting table

In this code, I will use the Pandas library to pivot a table. This is a common step that we typically need to perform in data analysis.

Here is a quick explanation and a tutorial about this:

In [1]:
# importing pandas

import pandas as pd

In [2]:
# loading the table

df = pd.read_csv('/kaggle/input/zon-usos/zon_usos2_202311301557.csv', sep=';', encoding='ISO8859-1')

In [3]:
# visualizing the first 10 registers

df.head(n=10)

,tp_uso,nm_uso,APL-E,APL-P,ARR,ARP,ARM,ATR,AMC,AMS,ZEIS,ARC,ATL,APT,AUE
0,Residenciais e habitacionais transitórios,Residências Unifamiliares,A,A,A,A,A,A,A,A,A,A,P,P,A
1,Residenciais e habitacionais transitórios,Condomínio de Lotes,A,P,P,P,P,P,P,P,P,P,P,P,P
2,Residenciais e habitacionais transitórios,Condomínio Residencial Multifamiliar Vertical,P,P,P,A-9,A,A,A,A,A,P,P,A,P
3,Residenciais e habitacionais transitórios,Condomínio Residencial Multifamiliar Horizontal,A,P,P,A,A,A,A,A,A,P,P,A,P
4,Residenciais e habitacionais transitórios,Hotéis Apart-hotel Hotel Fazenda e Pousadas,A,A,A,A-m,A,A,A,A,P,A-5-p,A-m,A,A
5,Residenciais e habitacionais transitórios,Albergues Pensões e Alojamentos,A,A,A,A-m,A,A,A,P,A,P,A-m,P,A
6,Residenciais e habitacionais transitórios,Campings,A,A,A,P,P,A,P,P,P,P,A-m,P,A
7,Residenciais e habitacionais transitórios,Móteis,A,A,P,P,P,P,A,A,P,P,P,P,A
8,Residenciais e habitacionais transitórios,Conventos e Seminários,A,A,A,A,A,A,A,P,P,A-p,P,P,A
9,Recreativos e esportivos,Circos parques temáticos e zoológicos,A-5,A,A,P,A,A,A,A,A-5,P,P,A,A

In [4]:
# viewing the columns from the table

print(df.columns)

Index(['tp_uso', 'nm_uso', 'APL-E', 'APL-P', 'ARR', 'ARP', 'ARM', 'ATR', 'AMC',
       'AMS', 'ZEIS', 'ARC', 'ATL', 'APT', 'AUE'],
      dtype='object')

In [5]:
# We will use the .shape to return the number of lines and columns:

df.shape

(109, 15)

**For this job, i need to insert the ['APL-E', 'APL-P', 'ARR', 'ARP', 'ARM', 'ATR', 'AMC',
       'AMS', 'ZEIS', 'ARC', 'ATL', 'APT', 'AUE'] in a column called by 'tp_zon'. **
       

**This is necessary for I can do a relation between other tables with the same structure, with 'tp_zon' columns.**

In [6]:
# creating a variable 'cols' with the columns that we will use in this pivoting

cols = ['APL-E', 'APL-P', 'ARR', 'ARP', 'ARM', 'ATR', 'AMC', 'AMS', 'ZEIS', 'ARC', 'ATL', 'APT', 'AUE', 'nm_uso', 'tp_uso']

In [7]:
# defining the index columns of the table

df[cols].set_index(['tp_uso', 'nm_uso']).head()

                                                                                          APL-E  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                           A
                                          Condomínio de Lotes                                 A
                                          Condomínio Residencial Multifamiliar Vertical       P
                                          Condomínio Residencial Multifamiliar Horizontal     A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas         A

                                                                                          APL-P  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                           A
                                          Condomínio de Lotes                                 P
                                          Condomínio Residencial Multifamiliar Vertical       P
                                          Condomínio Residencial Multifamiliar Horizontal     P
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas         A

                                                                                          ARR  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     P
                                          Condomínio Residencial Multifamiliar Horizontal   P
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                           ARP  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                          A
                                          Condomínio de Lotes                                P
                                          Condomínio Residencial Multifamiliar Vertical    A-9
                                          Condomínio Residencial Multifamiliar Horizontal    A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas      A-m

                                                                                          ARM  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     A
                                          Condomínio Residencial Multifamiliar Horizontal   A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                          ATR  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     A
                                          Condomínio Residencial Multifamiliar Horizontal   A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                          AMC  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     A
                                          Condomínio Residencial Multifamiliar Horizontal   A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                          AMS  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     A
                                          Condomínio Residencial Multifamiliar Horizontal   A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                          ZEIS  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                          A
                                          Condomínio de Lotes                                P
                                          Condomínio Residencial Multifamiliar Vertical      A
                                          Condomínio Residencial Multifamiliar Horizontal    A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas        P

                                                                                             ARC  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                            A
                                          Condomínio de Lotes                                  P
                                          Condomínio Residencial Multifamiliar Vertical        P
                                          Condomínio Residencial Multifamiliar Horizontal      P
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas      A-5-p

                                                                                           ATL  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                          P
                                          Condomínio de Lotes                                P
                                          Condomínio Residencial Multifamiliar Vertical      P
                                          Condomínio Residencial Multifamiliar Horizontal    P
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas      A-m

                                                                                          APT  \
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         P
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     A
                                          Condomínio Residencial Multifamiliar Horizontal   A
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

                                                                                          AUE
tp_uso                                    nm_uso
Residenciais e habitacionais transitórios Residências Unifamiliares                         A
                                          Condomínio de Lotes                               P
                                          Condomínio Residencial Multifamiliar Vertical     P
                                          Condomínio Residencial Multifamiliar Horizontal   P
                                          Hotéis Apart-hotel Hotel Fazenda e Pousadas       A

In [8]:
# here I use de list 'cols', setting the index a the 'tp_uso' and 'nm_uso' columns to the innermost levels of the columns, turning them into indices

df[cols].set_index(['tp_uso', 'nm_uso']).stack().head()

tp_uso                                     nm_uso
Residenciais e habitacionais transitórios  Residências Unifamiliares  APL-E    A
                                                                      APL-P    A
                                                                      ARR      A
                                                                      ARP      A
                                                                      ARM      A
dtype: object

In [9]:
# here I reset the index to show to me all the values of the lines

df[cols].set_index(['tp_uso', 'nm_uso']).stack().reset_index().head(n=10)

,tp_uso,nm_uso,level_2,0
0,Residenciais e habitacionais transitórios,Residências Unifamiliares,APL-E,A
1,Residenciais e habitacionais transitórios,Residências Unifamiliares,APL-P,A
2,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARR,A
3,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARP,A
4,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARM,A
5,Residenciais e habitacionais transitórios,Residências Unifamiliares,ATR,A
6,Residenciais e habitacionais transitórios,Residências Unifamiliares,AMC,A
7,Residenciais e habitacionais transitórios,Residências Unifamiliares,AMS,A
8,Residenciais e habitacionais transitórios,Residências Unifamiliares,ZEIS,A
9,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARC,A

In [10]:
# for finish, I create a df_result dataframe with the specific index and innermost levels.

df_result = df[cols].set_index(['tp_uso', 'nm_uso']).stack().reset_index()

# I give the name to columns 'tp_zon' and 'adequacao' like other tables witch I'll do the join

df_result.columns = ['tp_uso', 'nm_uso', 'tp_zon', 'adequacao']

# Let's see the result

df_result.head(n=10)

,tp_uso,nm_uso,tp_zon,adequacao
0,Residenciais e habitacionais transitórios,Residências Unifamiliares,APL-E,A
1,Residenciais e habitacionais transitórios,Residências Unifamiliares,APL-P,A
2,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARR,A
3,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARP,A
4,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARM,A
5,Residenciais e habitacionais transitórios,Residências Unifamiliares,ATR,A
6,Residenciais e habitacionais transitórios,Residências Unifamiliares,AMC,A
7,Residenciais e habitacionais transitórios,Residências Unifamiliares,AMS,A
8,Residenciais e habitacionais transitórios,Residências Unifamiliares,ZEIS,A
9,Residenciais e habitacionais transitórios,Residências Unifamiliares,ARC,A

In [11]:
# to finish, I save the table with the specif encoding, sep, and quotechar of our geodatabase

df_result.to_csv('zon_usos_transposta.csv', index=False, sep=';', encoding='ISO-8859-1', quotechar='"')